server:
  port: 3010
minio:
  url: http://8.134.81.197:9000
  accessKey: "minioroot"
  secretKey: "puname -rKs7GF"
storage:
  service:
    type: minio
logging:
  config: classpath:log4j2-spring.xml
spring:
  servlet:
    multipart:
      max-file-size: 50MB  #单个数据大小
      max-request-size: 100MB #总数据大小
